language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate
notifications:
  slack:
    secure: N0jvC2SL2nz9RKnuZ0gAsZibRzDaW68SKDVRj7Tr+aPPgmy1BlIa8R3tBw9PRhqhT6Vd4a2QoxJV+zyuVTcRPKpL7OSwWgP1EnsfMKdNGtgSl2TKAhu+9fsxf4Y685iwF7rOiHyPc1lEN6I/dKVrULcaxmjOOcKAm/SgivALzMHb+GKP26EoygeMdIYf7lcbmK+AXw4cYGfzKyWWjMZuDwVxBAUUgBgEm4RoAawRi/tIQ7Omqb0GX+Ld5LXZXztLeR3YILJdAOYnwAPWY9GG+CAE5FU5T8Tr8iS2lBljjNm0cKlkvJP2ZG6r8+ft07bm7jFUCZbDgzxNpTX40eJDpeX6MvfhsGeUKXSrYG3iXdCA9C1fxD0kBNc8Yd8TIkm/YKudfb5cnggyRzBZVdEszq/5y8yTFAFI8a+KqtExd1fKp03krw8HbZ8ja532issbcNxgibPCIV6yYUz8dVGjTJEaWJkEDPovqiElKPrDg050uqAB52QhUHx/LawvpJTB//TrbJG/Jz4oSpIhRa5ZH6LwzLkuhOUJhzobMxEgZXorDzaXpq01DUg4RpLg555p8uyaYwtirvJ76ZyU9liN66oCXxRRNdcTEhg0Iq6KtiUGmFn/Y5OA77uhkTZKyveOYvqfJbmz812U25hl1XFuuDp5qa883XqZYfn22AFmbSY=
